# Generated by Django 5.2.7 on 2025-10-22 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome do tipo de despesa', max_length=255, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do tipo de despesa', null=True, verbose_name='Descrição')),
                ('codigo', models.CharField(help_text='Código único para identificação', max_length=20, unique=True, verbose_name='Código')),
                ('categoria', models.CharField(choices=[('INSUMOS_AGRICOLAS', 'Insumos Agrícolas'), ('MANUTENCAO_OPERACAO', 'Manutenção e Operação'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('SERVICOS_OPERACIONAIS', 'Serviços Operacionais'), ('INFRAESTRUTURA_UTILIDADES', 'Infraestrutura e Utilidades'), ('ADMINISTRATIVAS', 'Administrativas'), ('SEGUROS_PROTECAO', 'Seguros e Proteção'), ('IMPOSTOS_TAXAS', 'Impostos e Taxas'), ('INVESTIMENTOS', 'Investimentos')], help_text='Categoria principal da despesa', max_length=50, verbose_name='Categoria')),
                ('cor', models.CharField(default='#dc3545', help_text='Cor para identificação visual (formato hex: #000000)', max_length=7, verbose_name='Cor')),
                ('palavras_chave', models.TextField(blank=True, help_text='Palavras-chave para classificação automática (separadas por vírgula)', null=True, verbose_name='Palavras-chave')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesa',
                'ordering': ['categoria', 'nome'],
                'indexes': [models.Index(fields=['nome'], name='tipos_despe_nome_dfc01a_idx'), models.Index(fields=['codigo'], name='tipos_despe_codigo_fef441_idx'), models.Index(fields=['categoria'], name='tipos_despe_categor_b1edfc_idx'), models.Index(fields=['ativo'], name='tipos_despe_ativo_8cc3cd_idx')],
            },
        ),
    ]
