# Generated by Django 4.2.7 on 2025-11-04 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturados', '0001_initial'),
        ('tipos_despesa', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('parcelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_nota_fiscal', models.CharField(help_text='Número da nota fiscal', max_length=50, verbose_name='Número da Nota Fiscal')),
                ('data_emissao', models.DateField(help_text='Data de emissão da nota fiscal', verbose_name='Data de Emissão')),
                ('descricao_produtos', models.TextField(help_text='Descrição dos produtos/serviços', verbose_name='Descrição dos Produtos')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total da conta', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Total')),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1, help_text='Quantidade de parcelas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Parcelas')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da conta', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('faturado', models.ForeignKey(help_text='Faturado da conta', on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='faturados.faturado')),
                ('fornecedor', models.ForeignKey(help_text='Fornecedor da conta', on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='fornecedores.fornecedor')),
                ('parcelas', models.ManyToManyField(blank=True, help_text='Parcelas da conta', related_name='contas_pagar', to='parcelas.parcela')),
                ('tipos_despesa', models.ManyToManyField(help_text='Classificação da despesa', related_name='contas_pagar', to='tipos_despesa.tipodespesa')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_emissao', '-criado_em'],
                'indexes': [models.Index(fields=['numero_nota_fiscal'], name='contas_paga_numero__906b1a_idx'), models.Index(fields=['data_emissao'], name='contas_paga_data_em_0ad8ec_idx'), models.Index(fields=['status'], name='contas_paga_status_a7e355_idx'), models.Index(fields=['fornecedor'], name='contas_paga_fornece_586f0a_idx'), models.Index(fields=['faturado'], name='contas_paga_faturad_21dd8d_idx'), models.Index(fields=['ativo'], name='contas_paga_ativo_1cc1a5_idx')],
            },
        ),
    ]
