# Generated by Django 5.2.7 on 2025-10-22 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome completo do cliente', max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='CPF no formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato', max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo', null=True, verbose_name='Endereço')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True, verbose_name='Data de Nascimento')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx'), models.Index(fields=['cpf'], name='clientes_cl_cpf_e6905f_idx'), models.Index(fields=['ativo'], name='clientes_cl_ativo_332763_idx')],
            },
        ),
    ]
