# Generated by Django 5.2.7 on 2025-10-22 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('razao_social', models.CharField(help_text='Razão social da empresa', max_length=255, unique=True, verbose_name='Razão Social')),
                ('fantasia', models.CharField(blank=True, help_text='Nome fantasia da empresa', max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(help_text='CNPJ no formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato', max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo', null=True, verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['razao_social'], name='fornecedore_razao_s_6d3c24_idx'), models.Index(fields=['cnpj'], name='fornecedore_cnpj_a9fb5e_idx'), models.Index(fields=['ativo'], name='fornecedore_ativo_602a05_idx')],
            },
        ),
    ]
