# Generated by Django 5.2.7 on 2025-11-09 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pergunta', models.TextField(help_text='Pergunta realizada pelo usuário', verbose_name='Pergunta')),
                ('tipo_rag', models.CharField(choices=[('SIMPLES', 'RAG Simples'), ('EMBEDDINGS', 'RAG com Embeddings')], default='SIMPLES', help_text='Tipo de RAG utilizado', max_length=20, verbose_name='Tipo de RAG')),
                ('contexto_retornado', models.TextField(blank=True, help_text='Contexto retornado pela busca RAG', null=True, verbose_name='Contexto Retornado')),
                ('resposta_llm', models.TextField(blank=True, help_text='Resposta elaborada pelo LLM', null=True, verbose_name='Resposta do LLM')),
                ('tempo_resposta', models.FloatField(blank=True, help_text='Tempo de processamento em segundos', null=True, verbose_name='Tempo de Resposta (segundos)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta RAG',
                'verbose_name_plural': 'Consultas RAG',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo_rag'], name='rag_consult_tipo_ra_0ef500_idx'), models.Index(fields=['criado_em'], name='rag_consult_criado__38e508_idx')],
            },
        ),
    ]
