# Generated by Django 5.2.7 on 2025-11-09 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('parcelas', '0001_initial'),
        ('tipos_receita', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_documento', models.CharField(help_text='Número do documento (nota fiscal, recibo, etc.)', max_length=50, verbose_name='Número do Documento')),
                ('data_emissao', models.DateField(help_text='Data de emissão do documento', verbose_name='Data de Emissão')),
                ('descricao', models.TextField(help_text='Descrição dos produtos/serviços', verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total da conta', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Total')),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1, help_text='Quantidade de parcelas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Parcelas')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da conta', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(help_text='Cliente da conta', on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('parcelas', models.ManyToManyField(blank=True, help_text='Parcelas da conta', related_name='contas_receber', to='parcelas.parcela')),
                ('tipos_receita', models.ManyToManyField(help_text='Classificação da receita', related_name='contas_receber', to='tipos_receita.tiporeceita')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_emissao', '-criado_em'],
                'indexes': [models.Index(fields=['numero_documento'], name='contas_rece_numero__b82934_idx'), models.Index(fields=['data_emissao'], name='contas_rece_data_em_3dbec1_idx'), models.Index(fields=['status'], name='contas_rece_status_c6650f_idx'), models.Index(fields=['cliente'], name='contas_rece_cliente_4b564e_idx'), models.Index(fields=['ativo'], name='contas_rece_ativo_e9d644_idx')],
            },
        ),
    ]
