# Generated by Django 5.2.7 on 2025-10-22 06:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('arquivo_pdf', models.FileField(help_text='Arquivo PDF da nota fiscal', upload_to='uploads/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Arquivo PDF')),
                ('nome_arquivo', models.CharField(help_text='Nome original do arquivo', max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_arquivo', models.BigIntegerField(help_text='Tamanho do arquivo em bytes', verbose_name='Tamanho do Arquivo')),
                ('status_processamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='PENDENTE', help_text='Status do processamento', max_length=20, verbose_name='Status do Processamento')),
                ('dados_extraidos', models.JSONField(blank=True, help_text='Dados extraídos do PDF em formato JSON', null=True, verbose_name='Dados Extraídos')),
                ('erro_processamento', models.TextField(blank=True, help_text='Mensagem de erro se houver', null=True, verbose_name='Erro no Processamento')),
                ('data_processamento', models.DateTimeField(blank=True, help_text='Data e hora do processamento', null=True, verbose_name='Data do Processamento')),
                ('tempo_processamento', models.DurationField(blank=True, help_text='Tempo gasto no processamento', null=True, verbose_name='Tempo de Processamento')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processamento de PDF',
                'verbose_name_plural': 'Processamentos de PDF',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status_processamento'], name='pdf_process_status__b454fd_idx'), models.Index(fields=['data_processamento'], name='pdf_process_data_pr_878d9e_idx'), models.Index(fields=['ativo'], name='pdf_process_ativo_d0fefb_idx')],
            },
        ),
    ]
