# Generated by Django 5.2.7 on 2025-10-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentopdf',
            name='status_processamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('DUPLICADO', 'Duplicado')], default='PENDENTE', help_text='Status do processamento', max_length=20, verbose_name='Status do Processamento'),
        ),
    ]
