# Generated by Django 4.2.7 on 2025-11-04 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_parcela', models.PositiveIntegerField(help_text='Número sequencial da parcela', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da Parcela')),
                ('data_vencimento', models.DateField(help_text='Data de vencimento da parcela', verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da parcela', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status da parcela', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data em que a parcela foi paga', null=True, verbose_name='Data de Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor efetivamente pago', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a parcela', null=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['data_vencimento', 'numero_parcela'],
                'indexes': [models.Index(fields=['data_vencimento'], name='parcelas_pa_data_ve_df30d4_idx'), models.Index(fields=['status'], name='parcelas_pa_status_80af86_idx'), models.Index(fields=['numero_parcela'], name='parcelas_pa_numero__42320c_idx'), models.Index(fields=['ativo'], name='parcelas_pa_ativo_c6c685_idx')],
            },
        ),
    ]
